name: 'Deploy'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.34.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Deploy To AWS
        run: pnpm deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
